// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Marcos  Oleniuk",
            "url": "https://wa.me/445598425745",
            "email": "marcos@moleniuk.comm"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Retorna informações básicas sobre a API de Loterias",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Root"
                ],
                "summary": "Informações da API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/{loteria}": {
            "get": {
                "description": "Retorna todos os resultados já realizados da loteria especificada",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loterias"
                ],
                "summary": "Busca resultados por loteria",
                "parameters": [
                    {
                        "enum": [
                            "maismilionaria",
                            "megasena",
                            "lotofacil",
                            "quina",
                            "lotomania",
                            "timemania",
                            "duplasena",
                            "federal",
                            "diadesorte",
                            "supersete"
                        ],
                        "type": "string",
                        "description": "ID da Loteria",
                        "name": "loteria",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Resultado"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{loteria}/latest": {
            "get": {
                "description": "Retorna o resultado mais recente da loteria especificada",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loterias"
                ],
                "summary": "Busca resultado mais recente",
                "parameters": [
                    {
                        "enum": [
                            "maismilionaria",
                            "megasena",
                            "lotofacil",
                            "quina",
                            "lotomania",
                            "timemania",
                            "duplasena",
                            "federal",
                            "diadesorte",
                            "supersete"
                        ],
                        "type": "string",
                        "description": "ID da Loteria",
                        "name": "loteria",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Resultado"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{loteria}/{concurso}": {
            "get": {
                "description": "Retorna o resultado da loteria e concurso especificado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Loterias"
                ],
                "summary": "Busca resultado por loteria e concurso",
                "parameters": [
                    {
                        "enum": [
                            "maismilionaria",
                            "megasena",
                            "lotofacil",
                            "quina",
                            "lotomania",
                            "timemania",
                            "duplasena",
                            "federal",
                            "diadesorte",
                            "supersete"
                        ],
                        "type": "string",
                        "description": "ID da Loteria",
                        "name": "loteria",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Número do Concurso",
                        "name": "concurso",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Resultado"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controller.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Estado": {
            "type": "object",
            "properties": {
                "ganhadores": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "uf": {
                    "type": "string"
                }
            }
        },
        "model.MunicipioUFGanhadores": {
            "type": "object",
            "properties": {
                "ganhadores": {
                    "type": "integer"
                },
                "municipio": {
                    "type": "string"
                },
                "numeroBilhete": {
                    "type": "string"
                },
                "posicao": {
                    "type": "integer"
                },
                "serie": {
                    "type": "string"
                },
                "uf": {
                    "type": "string"
                }
            }
        },
        "model.Premiacao": {
            "type": "object",
            "properties": {
                "descricao": {
                    "type": "string"
                },
                "faixa": {
                    "type": "integer"
                },
                "numeroDeGanhadores": {
                    "type": "integer"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "model.Resultado": {
            "type": "object",
            "properties": {
                "acumulou": {
                    "type": "boolean"
                },
                "concurso": {
                    "type": "integer"
                },
                "data": {
                    "type": "string"
                },
                "dataProximoConcurso": {
                    "type": "string"
                },
                "dezenas": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dezenasOrdemSorteio": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "estadosPremiados": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Estado"
                    }
                },
                "local": {
                    "type": "string"
                },
                "loteria": {
                    "type": "string"
                },
                "mesSorte": {
                    "type": "string"
                },
                "municipiosUFGanhadores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.MunicipioUFGanhadores"
                    }
                },
                "observacao": {
                    "type": "string"
                },
                "premiacoes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Premiacao"
                    }
                },
                "proximoConcurso": {
                    "type": "integer"
                },
                "timeCoracao": {
                    "type": "string"
                },
                "trevos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "valorAcumuladoConcursoEspecial": {
                    "type": "number"
                },
                "valorAcumuladoConcurso_0_5": {
                    "type": "number"
                },
                "valorAcumuladoProximoConcurso": {
                    "type": "number"
                },
                "valorArrecadado": {
                    "type": "number"
                },
                "valorEstimadoProximoConcurso": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api-loterias.moleniuk.com",
	BasePath:         "/api",
	Schemes:          []string{"https", "http"},
	Title:            "Loterias API Golang",
	Description:      "API para consulta de resultados de loterias da Caixa Econômica Federal",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
